### ISSUE TITLE
my repo is not searchable in dockerstats

### ISSUE THREAD

**Issue by sangshuduo** [aeneasr/dockerstats#1]
Hello there,

Dockerstats.com is really wonderful site I have been looking for. But I found my repo (tdengine/tdengine) is not searchable. Is it a bug?

**Comment by aeneasr** [comment]
When you search for a repository and it does not exist yet, it will be added to the index and fetched subsequently in future scrapings. Unfortunately there is no way to get historical data from the API which is why this limitation exists. If you check back in a week, there should be at least some data available!

**Comment by sangshuduo** [comment]
good to know. Thanks a lot!

**Comment by sangshuduo** [comment]
When I back to see the stat of the tdengine. What I see is just there are one day, 8/24 has data but no other days. Is it expected or a bug? thanks.

**Comment by aeneasr** [comment]
The queue is sometimes very long and needs a couple of days to catch up sometimes but i’ll investigate :)

**Comment by sangshuduo** [comment]
seems my repo never works. :(

**Comment by aeneasr** [comment]
Sorry about that, I will have to investigate what's causing the loop not to reach your image. Unfortunately I have very little free time at the moment so it'll probably take a while...

**Comment by aeneasr** [comment]
Hey there, the repo now appeared. I think the backlog is pretty huge now which causes repositories to be indexed like once a month maybe. I made some changes today that hopefully fix this but we'll see.

https://dockerstats.com/hubs/docker/tdengine/tdengine

**Comment by sangshuduo** [comment]
@aeneasr thanks!
