### ISSUE TITLE
[Feature Request] Select list of images to monitor

### ISSUE THREAD

**Issue by hferreira23** [aeneasr/dockerstats#2]
Hey,
Would it be possible to add a list of specific containers to monitor instead of the whole docker hub?

The idea is to self host and only monitor my containers.

**Comment by aeneasr** [comment]
Yes, I believe that is possible with the CLI! But I haven't checked yet...

**Comment by aeneasr** [comment]
This is actually not possible right now, so contributions towards such a feature would be welcomed!
